---
# tasks for: proxy

- name: Install nginx
  apt:
    name: nginx
    state: present
    force_apt_get: yes

- name: Install certbot
  apt:
    name: certbot
    state: present
    force_apt_get: yes

- name: Delete default site
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default
    - /var/www/html

- name: Create challenge directory
  file:
    path: /var/www/well-known
    state: directory

- name: Add http.conf
  copy:
    src: http.conf
    dest: "/etc/nginx/sites-available/http.conf"
  register: http_conf

- name: Enable http.conf
  file:
    src: "/etc/nginx/sites-available/http.conf"
    dest: "/etc/nginx/sites-enabled/http.conf"
    state: link

- name: Make sure nginx is running and enabled
  service:
    name: nginx
    state: reloaded
    enabled: yes
  when: http_conf.changed

- name: Add cron job for renewing certificates
  cron:
    name: "certbot renew"
    minute: "0"
    hour: "0"
    weekday: "0"
    job: "certbot renew -q --webroot -w /var/www/well-known/ --deploy-hook \"service nginx restart\""

- name: Create certificate
  command: certbot certonly --non-interactive --agree-tos --email snerhus@gmail.com --webroot -w /var/www/well-known/ -d "test.rygg-gaard.no"
  args:
    creates: "/etc/letsencrypt/live/test.rygg-gaard.no"
